// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CommitStudyLogs(arg1:Array<main.StudyLog>):Promise<string>;

export function GetRepoUrl():Promise<string>;

export function SetRepoUrl(arg1:string):Promise<void>;
