// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitStudyLogs(arg1) {
  return window['go']['main']['App']['CommitStudyLogs'](arg1);
}

export function GetRepoUrl() {
  return window['go']['main']['App']['GetRepoUrl']();
}

export function SetRepoUrl(arg1) {
  return window['go']['main']['App']['SetRepoUrl'](arg1);
}
